// Banque structurée du module Grammaire — V1.1.
// Une même phrase peut servir à plusieurs notions grâce aux annotations superposées.
function G_T(text){return {text:text}}
function G_D(text,type,gender,number,note){return {text:text,det:{type:type,gender:gender,number:number,note:note||""}}}
function G_N(text,type,gender,number,category){return {text:text,noun:{type:type,gender:gender,number:number,category:category||""}}}
function G_A(text,gender,number,category,position,noun){return {text:text,adj:{type:"qualificatif",gender:gender,number:number,category:category||"",position:position||"",noun:noun||""}}}
function G_P(level,kind,parts){return {level:level,kind:kind||"phrase",parts:parts}}
window.GRAMMAR_BANK=[
G_P(1,"phrase",[G_N("Léa","propre","féminin","singulier","prénom"),G_T(" regarde "),G_D("le","défini","masculin","singulier"),G_T(" "),G_N("chien","commun","masculin","singulier","animal"),G_T(" et "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("balle","commun","féminin","singulier","objet"),G_T(".")]),
G_P(1,"phrase",[G_T("À "),G_N("Montréal","propre","non évalué","singulier","ville"),G_T(", "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("tortue","commun","féminin","singulier","animal"),G_T(" mange "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("feuille","commun","féminin","singulier","végétal"),G_T(".")]),
G_P(1,"phrase",[G_D("Un","indéfini","masculin","singulier"),G_T(" "),G_N("oiseau","commun","masculin","singulier","animal"),G_T(" chante dans "),G_D("le","défini","masculin","singulier"),G_T(" "),G_N("jardin","commun","masculin","singulier","lieu"),G_T(".")]),
G_P(1,"phrase",[G_D("Les","défini","masculin","pluriel"),G_T(" "),G_N("enfants","commun","masculin","pluriel","personnes"),G_T(" rangent "),G_D("des","indéfini","masculin","pluriel"),G_T(" "),G_N("livres","commun","masculin","pluriel","objets"),G_T(".")]),
G_P(1,"phrase",[G_N("Mars","propre","masculin","singulier","planète"),G_T(" brille dans "),G_D("le","défini","masculin","singulier"),G_T(" "),G_N("ciel","commun","masculin","singulier","nature"),G_T(" près d’"),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("étoile","commun","féminin","singulier","astre"),G_T(".")]),
G_P(1,"phrase",[G_D("Le","défini","masculin","singulier"),G_T(" "),G_N("chat","commun","masculin","singulier","animal"),G_T(" dort sur "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("chaise","commun","féminin","singulier","mobilier"),G_T(".")]),
G_P(1,"phrase",[G_D("Des","indéfini","féminin","pluriel"),G_T(" "),G_N("pommes","commun","féminin","pluriel","aliments"),G_T(" sont dans "),G_D("le","défini","masculin","singulier"),G_T(" "),G_N("panier","commun","masculin","singulier","objet"),G_T(".")]),
G_P(1,"phrase",[G_D("Une","indéfini","féminin","singulier"),G_T(" "),G_N("grenouille","commun","féminin","singulier","animal"),G_T(" saute près de "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("rivière","commun","féminin","singulier","cours d’eau"),G_T(".")]),
G_P(1,"phrase",[G_D("Le","défini","masculin","singulier"),G_T(" "),G_N("garçon","commun","masculin","singulier","personne"),G_T(" ouvre "),G_D("un","indéfini","masculin","singulier"),G_T(" "),G_N("livre","commun","masculin","singulier","objet"),G_T(".")]),
G_P(1,"phrase",[G_N("Zoé","propre","féminin","singulier","prénom"),G_T(" dessine "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("planète","commun","féminin","singulier","astre"),G_T(" sur "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("table","commun","féminin","singulier","mobilier"),G_T(".")]),
G_P(1,"phrase",[G_D("Un","indéfini","masculin","singulier"),G_T(" "),G_N("ballon","commun","masculin","singulier","objet"),G_T(" roule sous "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("table","commun","féminin","singulier","mobilier"),G_T(".")]),
G_P(1,"phrase",[G_D("Les","défini","féminin","pluriel"),G_T(" "),G_N("étoiles","commun","féminin","pluriel","astres"),G_T(" éclairent "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("nuit","commun","féminin","singulier","moment du temps"),G_T(".")]),

G_P(2,"phrase",[G_N("Hugo","propre","masculin","singulier","prénom"),G_T(" range "),G_D("ses","possessif","masculin","pluriel"),G_T(" "),G_N("livres","commun","masculin","pluriel","objets"),G_T(" dans "),G_D("son","possessif","masculin","singulier"),G_T(" "),G_N("sac","commun","masculin","singulier","objet"),G_T(".")]),
G_P(2,"phrase",[G_N("Zoé","propre","féminin","singulier","prénom"),G_T(" prépare "),G_D("sa","possessif","féminin","singulier"),G_T(" "),G_N("collation","commun","féminin","singulier","aliment"),G_T(" avec "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("pomme","commun","féminin","singulier","aliment"),G_T(".")]),
G_P(2,"phrase",[G_T("À "),G_N("Québec","propre","non évalué","singulier","ville"),G_T(", "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_N("tortue","commun","féminin","singulier","animal"),G_T(" avance vers "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("rivière","commun","féminin","singulier","cours d’eau"),G_T(".")]),
G_P(2,"phrase",[G_D("Ces","démonstratif","masculin","pluriel"),G_T(" "),G_N("oiseaux","commun","masculin","pluriel","animaux"),G_T(" construisent "),G_D("leur","possessif","masculin","singulier"),G_T(" "),G_N("nid","commun","masculin","singulier","abri animal"),G_T(".")]),
G_P(2,"phrase",[G_N("Arthur","propre","masculin","singulier","prénom"),G_T(" apporte "),G_D("son","possessif","masculin","singulier"),G_T(" "),G_N("ballon","commun","masculin","singulier","objet"),G_T(" sur "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("terrain","commun","masculin","singulier","lieu"),G_T(".")]),
G_P(2,"phrase",[G_D("Ma","possessif","féminin","singulier"),G_T(" "),G_N("sœur","commun","féminin","singulier","personne"),G_T(" lit "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("livre","commun","masculin","singulier","objet"),G_T(" près de "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("fenêtre","commun","féminin","singulier","partie d’un bâtiment"),G_T(".")]),
G_P(2,"phrase",[G_D("Notre","possessif","féminin","singulier"),G_T(" "),G_N("classe","commun","féminin","singulier","groupe scolaire"),G_T(" visite "),G_D("un","indéfini","masculin","singulier"),G_T(" "),G_N("musée","commun","masculin","singulier","lieu"),G_T(" "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_N("semaine","commun","féminin","singulier","mesure du temps"),G_T(".")]),
G_P(2,"phrase",[G_D("Mes","possessif","masculin","pluriel"),G_T(" "),G_N("crayons","commun","masculin","pluriel","outils scolaires"),G_T(" sont dans "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_N("boîte","commun","féminin","singulier","objet"),G_T(".")]),
G_P(2,"phrase",[G_D("Ton","possessif","masculin","singulier"),G_T(" "),G_N("chien","commun","masculin","singulier","animal"),G_T(" suit "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("sentier","commun","masculin","singulier","chemin"),G_T(".")]),
G_P(2,"phrase",[G_D("Ces","démonstratif","féminin","pluriel"),G_T(" "),G_N("photos","commun","féminin","pluriel","objets"),G_T(" montrent "),G_D("nos","possessif","féminin","pluriel"),G_T(" "),G_N("vacances","commun","féminin","pluriel","période"),G_T(".")]),
G_P(2,"phrase",[G_N("Camille","propre","non évalué","singulier","prénom"),G_T(" pose "),G_D("sa","possessif","féminin","singulier"),G_T(" "),G_N("carte","commun","féminin","singulier","objet"),G_T(" sur "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("table","commun","féminin","singulier","mobilier"),G_T(".")]),
G_P(2,"phrase",[G_T("Au "),G_N("Canada","propre","masculin","singulier","pays"),G_T(", "),G_D("cet","démonstratif","masculin","singulier"),G_T(" "),G_N("arbre","commun","masculin","singulier","végétal"),G_T(" abrite "),G_D("des","indéfini","masculin","pluriel"),G_T(" "),G_N("oiseaux","commun","masculin","pluriel","animaux"),G_T(".")]),

G_P(3,"phrase",[G_D("Quel","interrogatif","masculin","singulier"),G_T(" "),G_N("animal","commun","masculin","singulier","animal"),G_T(" laisse "),G_D("ces","démonstratif","féminin","pluriel"),G_T(" "),G_N("traces","commun","féminin","pluriel","indices"),G_T(" dans "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("boue","commun","féminin","singulier","matière naturelle"),G_T(" ?")]),
G_P(3,"phrase",[G_T("Près de "),G_N("Saturne","propre","féminin","singulier","planète"),G_T(", "),G_D("quelle","interrogatif","féminin","singulier"),G_T(" "),G_N("planète","commun","féminin","singulier","astre"),G_T(" possède aussi "),G_D("des","indéfini","masculin","pluriel"),G_T(" "),G_N("anneaux","commun","masculin","pluriel","structure planétaire"),G_T(" ?")]),
G_P(3,"phrase",[G_T("Dans les "),G_N("Laurentides","propre","féminin","pluriel","région"),G_T(", "),G_D("plusieurs","autre","masculin","pluriel","quantité"),G_T(" "),G_N("élèves","commun","masculin","pluriel","personnes"),G_T(" rangent "),G_D("leurs","possessif","masculin","pluriel"),G_T(" "),G_N("cahiers","commun","masculin","pluriel","outils scolaires"),G_T(".")]),
G_P(3,"phrase",[G_D("Quelques","autre","féminin","pluriel","quantité"),G_T(" "),G_N("étoiles","commun","féminin","pluriel","astres"),G_T(" brillent derrière "),G_D("les","défini","masculin","pluriel"),G_T(" "),G_N("nuages","commun","masculin","pluriel","phénomènes météorologiques"),G_T(".")]),
G_P(3,"phrase",[G_D("Chaque","autre","masculin","singulier","distribution"),G_T(" "),G_N("campeur","commun","masculin","singulier","personne"),G_T(" prépare "),G_D("son","possessif","masculin","singulier"),G_T(" "),G_N("sac","commun","masculin","singulier","objet"),G_T(" avant "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("randonnée","commun","féminin","singulier","activité"),G_T(".")]),
G_P(3,"phrase",[G_D("Aucune","autre","féminin","singulier","quantité nulle"),G_T(" "),G_N("lumière","commun","féminin","singulier","phénomène physique"),G_T(" ne traverse "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_N("boîte","commun","féminin","singulier","objet"),G_T(" fermée.")]),
G_P(3,"phrase",[G_N("Thomas","propre","masculin","singulier","prénom"),G_T(" place "),G_D("trois","numéral","féminin","pluriel"),G_T(" "),G_N("planètes","commun","féminin","pluriel","astres"),G_T(" sur "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_N("carte","commun","féminin","singulier","objet"),G_T(".")]),
G_P(3,"phrase",[G_D("Deux","numéral","masculin","pluriel"),G_T(" "),G_N("dauphins","commun","masculin","pluriel","animaux"),G_T(" suivent "),G_D("le","défini","masculin","singulier"),G_T(" "),G_N("bateau","commun","masculin","singulier","véhicule"),G_T(".")]),
G_P(3,"phrase",[G_D("Quels","interrogatif","masculin","pluriel"),G_T(" "),G_N("objets","commun","masculin","pluriel","objets"),G_T(" dois-tu placer dans "),G_D("ton","possessif","masculin","singulier"),G_T(" "),G_N("sac","commun","masculin","singulier","objet"),G_T(" ?")]),
G_P(3,"phrase",[G_D("Quelles","interrogatif","féminin","pluriel"),G_T(" "),G_N("étoiles","commun","féminin","pluriel","astres"),G_T(" vois-tu dans "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("ciel","commun","masculin","singulier","nature"),G_T(" ?")]),
G_P(3,"phrase",[G_T("À "),G_N("Montréal","propre","non évalué","singulier","ville"),G_T(", "),G_D("plusieurs","autre","féminin","pluriel","quantité"),G_T(" "),G_N("familles","commun","féminin","pluriel","groupes de personnes"),G_T(" observent "),G_D("les","défini","féminin","pluriel"),G_T(" "),G_N("aurores","commun","féminin","pluriel","phénomènes naturels"),G_T(" pendant "),G_D("leur","possessif","masculin","singulier"),G_T(" "),G_N("voyage","commun","masculin","singulier","activité"),G_T(".")]),
G_P(3,"phrase",[G_D("Quelques","autre","masculin","pluriel","quantité"),G_T(" "),G_N("indices","commun","masculin","pluriel","indices"),G_T(" permettent de résoudre "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("mystère","commun","masculin","singulier","idée / énigme"),G_T(".")]),
G_P(1,"phrase",[G_D("Le","défini","masculin","singulier"),G_T(" "),G_A("petit","masculin","singulier","taille","avant","chat"),G_T(" "),G_N("chat","commun","masculin","singulier","animal"),G_T(" dort.")]),
G_P(1,"phrase",[G_D("La","défini","féminin","singulier"),G_T(" "),G_N("fleur","commun","féminin","singulier","végétal"),G_T(" "),G_A("rouge","féminin","singulier","couleur","après","fleur"),G_T(" pousse.")]),
G_P(1,"phrase",[G_D("Un","indéfini","masculin","singulier"),G_T(" "),G_N("ballon","commun","masculin","singulier","objet"),G_T(" "),G_A("rond","masculin","singulier","forme","après","ballon"),G_T(" roule.")]),
G_P(1,"phrase",[G_D("Une","indéfini","féminin","singulier"),G_T(" "),G_A("grande","féminin","singulier","taille","avant","maison"),G_T(" "),G_N("maison","commun","féminin","singulier","bâtiment"),G_T(" apparaît au loin.")]),
G_P(1,"phrase",[G_D("Le","défini","masculin","singulier"),G_T(" "),G_N("chien","commun","masculin","singulier","animal"),G_T(" "),G_A("noir","masculin","singulier","couleur","après","chien"),G_T(" court.")]),
G_P(1,"phrase",[G_D("Une","indéfini","féminin","singulier"),G_T(" "),G_A("chaude","féminin","singulier","température","avant","soupe"),G_T(" "),G_N("soupe","commun","féminin","singulier","aliment"),G_T(" attend sur "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("table","commun","féminin","singulier","mobilier"),G_T(".")]),

G_P(2,"phrase",[G_N("Léa","propre","féminin","singulier","prénom"),G_T(" observe "),G_D("un","indéfini","masculin","singulier"),G_T(" "),G_A("grand","masculin","singulier","taille","avant","oiseau"),G_T(" "),G_N("oiseau","commun","masculin","singulier","animal"),G_T(" "),G_A("bleu","masculin","singulier","couleur","après","oiseau"),G_T(".")]),
G_P(2,"phrase",[G_D("Cette","démonstratif","féminin","singulier"),G_T(" "),G_N("route","commun","féminin","singulier","voie"),G_T(" "),G_A("étroite","féminin","singulier","dimension","après","route"),G_T(" traverse "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_A("belle","féminin","singulier","appréciation","avant","forêt"),G_T(" "),G_N("forêt","commun","féminin","singulier","lieu naturel"),G_T(".")]),
G_P(2,"phrase",[G_D("Quel","interrogatif","masculin","singulier"),G_T(" "),G_A("petit","masculin","singulier","taille","avant","animal"),G_T(" "),G_N("animal","commun","masculin","singulier","animal"),G_T(" porte "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("carapace","commun","féminin","singulier","partie du corps"),G_T(" "),G_A("dure","féminin","singulier","propriété","après","carapace"),G_T(" ?")]),
G_P(2,"phrase",[G_D("Les","défini","féminin","pluriel"),G_T(" "),G_A("jeunes","féminin","pluriel","âge","avant","tortues"),G_T(" "),G_N("tortues","commun","féminin","pluriel","animaux"),G_T(" rejoignent "),G_D("la","défini","féminin","singulier"),G_T(" "),G_N("mer","commun","féminin","singulier","lieu naturel"),G_T(" "),G_A("calme","féminin","singulier","état","après","mer"),G_T(".")]),
G_P(2,"phrase",[G_N("Mars","propre","masculin","singulier","planète"),G_T(" semble "),G_A("rouge","masculin","singulier","couleur","après le verbe","Mars"),G_T(" dans "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_A("vaste","masculin","singulier","dimension","avant","ciel"),G_T(" "),G_N("ciel","commun","masculin","singulier","nature"),G_T(".")]),
G_P(2,"phrase",[G_D("Ces","démonstratif","masculin","pluriel"),G_T(" "),G_N("rochers","commun","masculin","pluriel","éléments naturels"),G_T(" "),G_A("gris","masculin","pluriel","couleur","après","rochers"),G_T(" bordent "),G_D("un","indéfini","masculin","singulier"),G_T(" "),G_A("long","masculin","singulier","dimension","avant","sentier"),G_T(" "),G_N("sentier","commun","masculin","singulier","chemin"),G_T(".")]),

G_P(3,"phrase",[G_D("Quelle","interrogatif","féminin","singulier"),G_T(" "),G_A("immense","féminin","singulier","dimension","avant","planète"),G_T(" "),G_N("planète","commun","féminin","singulier","astre"),G_T(" possède "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("tache","commun","féminin","singulier","marque"),G_T(" "),G_A("rouge","féminin","singulier","couleur","après","tache"),G_T(" ?")]),
G_P(3,"phrase",[G_D("Quels","interrogatif","masculin","pluriel"),G_T(" "),G_A("anciens","masculin","pluriel","âge","avant","ponts"),G_T(" "),G_N("ponts","commun","masculin","pluriel","constructions"),G_T(" sont encore "),G_A("solides","masculin","pluriel","état","après le verbe","ponts"),G_T(" ?")]),
G_P(3,"phrase",[G_T("Dans "),G_D("cette","démonstratif","féminin","singulier"),G_T(" "),G_A("sombre","féminin","singulier","luminosité","avant","forêt"),G_T(" "),G_N("forêt","commun","féminin","singulier","lieu naturel"),G_T(", "),G_D("les","défini","masculin","pluriel"),G_T(" "),G_N("arbres","commun","masculin","pluriel","végétaux"),G_T(" "),G_A("géants","masculin","pluriel","taille","après","arbres"),G_T(" cachent "),G_D("un","indéfini","masculin","singulier"),G_T(" "),G_A("petit","masculin","singulier","taille","avant","ruisseau"),G_T(" "),G_N("ruisseau","commun","masculin","singulier","cours d’eau"),G_T(".")]),
G_P(3,"phrase",[G_D("Quelles","interrogatif","féminin","pluriel"),G_T(" "),G_N("étoiles","commun","féminin","pluriel","astres"),G_T(" "),G_A("brillantes","féminin","pluriel","luminosité","après","étoiles"),G_T(" vois-tu dans "),G_D("ce","démonstratif","masculin","singulier"),G_T(" "),G_N("ciel","commun","masculin","singulier","nature"),G_T(" "),G_A("nocturne","masculin","singulier","temps","après","ciel"),G_T(" ?")]),
G_P(3,"phrase",[G_N("Thomas","propre","masculin","singulier","prénom"),G_T(" ouvre "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_A("vieille","féminin","singulier","âge","avant","porte"),G_T(" "),G_N("porte","commun","féminin","singulier","partie d’un bâtiment"),G_T(" "),G_A("fermée","féminin","singulier","état","après","porte"),G_T(" et découvre "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_N("pièce","commun","féminin","singulier","lieu"),G_T(" "),G_A("secrète","féminin","singulier","caractéristique","après","pièce"),G_T(".")]),
G_P(3,"phrase",[G_D("Cette","démonstratif","féminin","singulier"),G_T(" "),G_A("curieuse","féminin","singulier","caractère","avant","exploratrice"),G_T(" "),G_N("exploratrice","commun","féminin","singulier","personne"),G_T(" trouve "),G_D("des","indéfini","masculin","pluriel"),G_T(" "),G_N("indices","commun","masculin","pluriel","indices"),G_T(" "),G_A("étranges","masculin","pluriel","caractéristique","après","indices"),G_T(" sous "),G_D("une","indéfini","féminin","singulier"),G_T(" "),G_A("lourde","féminin","singulier","poids","avant","pierre"),G_T(" "),G_N("pierre","commun","féminin","singulier","matière naturelle"),G_T(".")])

];
